apiVersion: v1
kind: Pod
metadata:
  name: ebpf-profiler
spec:
  hostPID: true
  containers:
  - name: ebpf-profiler
    image: aimvector/flamegraph
    imagePullPolicy: Always
    securityContext:
      privileged: true
    command: ["/bin/bash"]
    args: ["-c", "tail -f /dev/null"]
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker
      - mountPath: /sys/kernel/debug
        name: kernel-debug
      - mountPath: /sys/fs/cgroup
        name: fs-cgroup
      - mountPath: /sys/fs/bpf
        name: fs-bpf
      - mountPath: /lib/modules
        name: lib-modules
  nodeSelector:
    kubernetes.io/hostname: k8s-agentpool2-34804781-0 # you can bind to a specific agent
  volumes:
    - name: docker
      hostPath: 
        path: /var/run/docker.sock
    - name: kernel-debug
      hostPath:
        path: /sys/kernel/debug
    - name: fs-cgroup
      hostPath:
        path: /sys/fs/cgroup
    - name: fs-bpf
      hostPath:
        path: /sys/fs/bpf
    - name: lib-modules
      hostPath:
        path: /lib/modules