apiVersion: v1
kind: Pod
metadata:
  name: perf
spec:
  hostIPC: true
  hostPID: true
  containers:
  - name: perf
    image: aimvector/dotnet-perf:4.15.1
    imagePullPolicy: Always
    securityContext:
      privileged: true
    command: ["/bin/bash"]
    args: ["-c", "tail -f /dev/null"]
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker
      - mountPath: /tmp
        name: tmp
      - mountPath: /proc/stat
        name: stat
  nodeSelector:
    kubernetes.io/hostname: k8s-agentpool2-34804781-0 # you can bind to a specific agent
  volumes:
    - name: docker
      hostPath: 
        path: /var/run/docker.sock
    - name: tmp
      hostPath:
        path: /tmp
    - name: stat
      hostPath:
        path: /proc/stat